export const EXAMPLE = 'example'
export const ASSERTION = 'assertion'
export const VARIABLE = 'variable'
export const FUNCTION = 'function'
export const EMPTY = ''
export const FUNCTION_PREFIX = 'Fixture'